# Programación 201

Librerías científicas en Python: `NumPy`
------------------------------------------------------

### Ejercicio 1
Calculad la norma y el determinante de la siguiente matriz: ```[[1, 0], [2, -1]]```.

In [1]:
# Importamos la librería numpy.
import numpy as np

In [2]:
# Creamos la matriz.
matriz_one = np.array([[1, 0], [2, -1]])

# Calculamos la norma con la función `linalg.norm` y la mostramos por pantalla.
norm = np.linalg.norm(matriz_one)
print("La norma de la matriz es: " + str(norm))

# Calculamos el determinante con la función `linalg.det` y lo mostramos por pantalla.
det = np.linalg.det(matriz_one)
print("El determinante de la matriz es: " + str(det))

La norma de la matriz es: 2.449489742783178
El determinante de la matriz es: -1.0


### Ejercicio 2 
Evaluad las funciones arcoseno y arcocoseno en el intervalo [0,1] y con paso (resolución) de 0.1 y guardadlas en dos _arrays_.

In [3]:
# Evaluamos la función del arcoseno en el intervano [0,1] y con paso de 0.1.
array_one = np.array([[]])
for i in np.arange(0, 1, 0.1):
    # Utilizamos la función de numpy `arange` que soporta números flotantes.
    array_one =  np.append(array_one, np.arcsin(i))

# Mostramos por pantalla el resultado.
print("El array resultante de aplicar la función de arcoseno en el intervalo [0,1] con paso 0.1 es: \n" + str(array_one))

El array resultante de aplicar la función de arcoseno en el intervalo [0,1] con paso 0.1 es: 
[0.         0.10016742 0.20135792 0.30469265 0.41151685 0.52359878
 0.64350111 0.7753975  0.92729522 1.11976951]


In [4]:
# Evaluamos la función del arcocoseno en el intervano [0,1] y con paso de 0.1.
array_two = np.array([[]])
for i in np.arange(0, 1, 0.1):
    # Utilizamos la función de numpy `arange` que soporta números flotantes.
    array_two = np.append(array_two, np.arccos(i))
    
# Mostramos por pantalla el resultado.
print("El array resultante de aplicar la función de arcocoseno en el intervalo [0,1] con paso 0.1 es: \n" + str(array_two))

El array resultante de aplicar la función de arcocoseno en el intervalo [0,1] con paso 0.1 es: 
[1.57079633 1.47062891 1.36943841 1.26610367 1.15927948 1.04719755
 0.92729522 0.79539883 0.64350111 0.45102681]


### Ejercicio 3
Generad una lista de 100 valores enteros aleatorios de 0-9. Realizad los siguientes cálculos utilizando métodos de _numpy_:
- Media y desviación estándar de los valores de la lista
- Valor máximo y mínimo
- Sumad todos los valores de la lista
- Conseguid una lista de valores únicos

In [5]:
# Utilizando la función `random.randint` generamos una lista de 100 valores enteros aleatorios de 0 a 9, el parámetro `size`
# determina el tamaño de la lista y hay que tener en cuenta que el último número del rango seleccionado queda excluido, por lo
# que ponemos como último número el 10 para que el 9 sea también seleccionado.
list_random_values_0_to_9 = np.random.randint(0, 10, size = 100)
list_random_values_0_to_9

array([0, 7, 0, 6, 9, 5, 3, 0, 1, 5, 8, 8, 1, 5, 7, 3, 4, 3, 8, 6, 8, 1,
       7, 3, 0, 5, 6, 9, 6, 6, 0, 6, 7, 2, 6, 9, 6, 4, 9, 3, 5, 7, 7, 1,
       2, 1, 3, 0, 0, 6, 4, 6, 2, 2, 2, 0, 1, 6, 8, 5, 8, 3, 0, 2, 9, 1,
       1, 9, 5, 1, 0, 4, 9, 6, 0, 1, 8, 4, 6, 4, 5, 6, 0, 6, 0, 0, 7, 9,
       8, 4, 2, 9, 8, 5, 6, 7, 4, 0, 0, 6])

In [6]:
# Calculamos los distintos valores estadísticos sobre la lista.
print("La media de los valores de la lista es: " + str(np.mean(list_random_values_0_to_9)))
print("La desviación típica de los valores de la lista es: " + str(np.std(list_random_values_0_to_9)))
print("El máximo de los valores de la lista es: " + str(np.amax(list_random_values_0_to_9)))
print("El mínimo de los valores de la lista es: " + str(np.amin(list_random_values_0_to_9)))
print("La suma de los valores de la lista es: " + str(np.sum(list_random_values_0_to_9)))
print("Una lista de valores únicos de esta lista sería: " + str(np.unique(list_random_values_0_to_9)))

La media de los valores de la lista es: 4.33
La desviación típica de los valores de la lista es: 2.98011744735002
El máximo de los valores de la lista es: 9
El mínimo de los valores de la lista es: 0
La suma de los valores de la lista es: 433
Una lista de valores únicos de esta lista sería: [0 1 2 3 4 5 6 7 8 9]


### Ejercicio 4
Ordenad la matriz bidimensional ```[[5,1,7], [0,7,4], [7,23,1]]``` por filas utilizando como algoritmo de ordenación el [Merge sort](https://en.wikipedia.org/wiki/Merge_sort).

**Hint:** No es necesario que implementéis el algoritmo de ordenación a mano, NumPy contiene métodos para realizar diferentes tipos de ordenación sobre diferentes estructuras de datos.

In [7]:
# Creamos la matriz bidimensional y la mostramos por pantalla.
matriz_bidimensional = np.array([[5,1,7], [0,7,4], [7,23,1]])
print(matriz_bidimensional)

[[ 5  1  7]
 [ 0  7  4]
 [ 7 23  1]]


In [8]:
# Ordenamos la matriz anterior utilizando la función `sort`, pasando como parámetro el algoritmo de ordenación "Merge sort" y
# estableciendo la orientación por filas con el parámetro "axis".
sorted_matrix = np.sort(matriz_bidimensional, axis = 0, kind = 'mergesort')

# Mostramos por pantalla el resultado.
print(sorted_matrix)

[[ 0  1  1]
 [ 5  7  4]
 [ 7 23  7]]


### Ejercicio 5
Definid una función que dadas dos matrices, devuelva el valor absoluto de la multiplicación de los determinantes ambas, es decir, dadas A y B, nuestra función devolverá `|det(A) * det(B)|`.

In [9]:
# Creamos una función que dadas dos matrices, devuelva el valor absoluto de la multiplicación de los determinantes de ambas.
def abs_value_product_det(matrix_a, matrix_b):
    product_matrix_det = np.linalg.det(matrix_a) * np.linalg.det(matrix_b)
    return np.absolute(product_matrix_det)

# Creamos dos matrices A y B.
a = np.array([[1, 4], [7, 4]])
b = np.array([[3, 5], [2, 3]])

# Llamamos a la función para comprobar que funciona correctamente.
abs_value_product_det(a, b)

23.999999999999982

### Ejercicio 6
Cread una matriz 10x10 que corresponda con la [matriz identidad](https://es.wikipedia.org/wiki/Matriz_identidad) usando generadores básicos de arrays. Cread una matriz identidad 10x10 (esta vez usando generadores especificos de matrices identidad) y comprobad que ambas matrices son iguales

**Consideraciones**:
- La primera matriz debe crearse usando constructores básicos de arrays, como los presentados en los Notebooks de teoría.
* La segunda matriz debe generarse utilizando el generador de matrices identidad de numpy.
* La comparación debe devolver True si las matrices son iguales (un único True), False de no ser así.

In [10]:
# Creamos una matriz 10x10 con generadores básicos de arrays y mostramos por pantalla.
basic_matrix = np.zeros(shape = [10, 10])
for i in range(10):
    basic_matrix[i][i] = 1
    
basic_matrix

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [11]:
# Creamos una matriz 10x10 con generadores específicos de matrices identidad y mostramos por pantalla.
identity_matrix = np.identity(10)
identity_matrix

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [12]:
# Creamos una función que compruebe si las dos matrices son iguales:
def compare_function():
    compare = False
    # Comprobamos si las dimensiones de las matrices y los elementos que contienen son iguales, para ello usamos las funciones
    # `shape` y `all`, respectivamente.
    if basic_matrix.shape == identity_matrix.shape and (basic_matrix == identity_matrix).all():
        compare = True
    return compare

# Llamamos a la función.
compare_function()

True

### Ejercicio 7
Cread una matriz de 2x6 donde los valores de cada posición `(i, j)` correspondan a `i^2+j` para todo `i` par, `i/j^2` para todo `i` impar.

In [13]:
# Creamos una matriz de tamaño 2x6 con la función `zeros`.
matrix_2_x_6 = np.zeros(shape = (2, 6))

# Utilizamos dos bucles for para recorrer la matriz.
for i in range(2):
    for j in range(6):
        # Establecemos la condición de si "i" es par, y le aplicamos en dicho caso a la matriz la transformación correspondiente.
        # Ya que en matemáticas los índices empiezan en 1, tenemos que sumarle 1 a la i y a la j cuando operamos con ellas para
        # que las fórmulas funcionen correctamente y los datos sean correctos.
        if (i + 1) % 2 == 0:
            matrix_2_x_6[i][j] = (i + 1)**2 + (j + 1)
        # En caso contrario (caso de ser "i" impar), le aplicamos la otra transformación que corresponde.
        else:
            matrix_2_x_6[i][j] = (i + 1) / (j + 1)**2
            
# Mostramos la matriz resultante.
matrix_2_x_6

array([[ 1.        ,  0.25      ,  0.11111111,  0.0625    ,  0.04      ,
         0.02777778],
       [ 5.        ,  6.        ,  7.        ,  8.        ,  9.        ,
        10.        ]])

### Ejercicio 8
Cread dos matrices de tamaño 5x5 con números reales aleatorios. Obtened el resultado de multiplicar ambas matrices usando los dos métodos de multiplicación de matrices vistos en el Notebook de teoría. ¿Cuál es la diferencia entre ambos resultados? Cread ahora dos matrices de tamaño 4x5 y 5x5 respectivamente, repetid la operación. Describid cuál de los métodos de multiplicación podéis aplicar y porqué

In [14]:
# Creamos dos matrices 5x5 con números reales aleatorios con la función `random.choice`.
matrix_5x5_one = np.random.rand(5, 5)
matrix_5x5_two = np.random.rand(5, 5)

# Mostramos por pantalla ambas matrices.
print(matrix_5x5_one)
print(matrix_5x5_two)

[[0.15288118 0.82429941 0.47048116 0.87121754 0.00458208]
 [0.47366722 0.48188018 0.87641423 0.14023366 0.31082824]
 [0.16570055 0.29300236 0.61985489 0.60465234 0.43048782]
 [0.90238478 0.8974447  0.0928889  0.13437475 0.03806194]
 [0.25185801 0.27471816 0.93594968 0.62769514 0.53448775]]
[[0.87975285 0.92530759 0.71970057 0.10307489 0.77904412]
 [0.94119099 0.97150959 0.15245858 0.30880671 0.74629854]
 [0.61670129 0.84243215 0.94651505 0.20892298 0.13722413]
 [0.87956364 0.72159802 0.74200376 0.29904605 0.22797826]
 [0.39172967 0.83434892 0.6741173  0.41582232 0.82847651]]


In [15]:
# Multiplicamos ambas matrices por el método uno, usando el operador "*".
matrix_product_one = matrix_5x5_one * matrix_5x5_two

# Multiplicamos ambas matrices por el método dos, usando la función `dot`.
matrix_product_two = matrix_5x5_one.dot(matrix_5x5_two)

# Mostramos el resultado de ambas multiplicaciones para ver la diferencia y vemos que sí la hay. Por un lado, el primer método
# devuelve un array con la multiplicación de ambas matrices elemento a elemento y por otro lado, el segundo método aplica el 
# procedimiento matemático del producto matricial.
print("El resultado del primer método para multiplicar matrices es: \n" + str(matrix_product_one))
print("El resultado del segundo método para multiplicar matrices es: \n" + str(matrix_product_two))

El resultado del primer método para multiplicar matrices es: 
[[0.13449766 0.7627305  0.33860556 0.08980065 0.00356964]
 [0.44581132 0.46815121 0.13361687 0.0433051  0.23197066]
 [0.10218774 0.24683461 0.58670198 0.12632577 0.05907332]
 [0.79370484 0.64759431 0.06892391 0.04018424 0.0086773 ]
 [0.09866026 0.22921081 0.63093987 0.26100965 0.44281055]]
El resultado del segundo método para multiplicar matrices es: 
[[1.96855337 1.97111725 1.33055324 0.63104122 1.0012508 ]
 [1.65584223 2.00529015 1.55749319 0.55191975 1.13838344]
 [1.50427709 1.75565724 1.48948108 0.59688793 0.92731095]
 [1.82892828 1.91383371 0.99955551 0.44556803 1.44767377]
 [1.81880898 2.18730441 1.93509555 0.71629814 1.11557654]]


In [16]:
# Creamos dos matrices, una 4x5 y otra 5x5, con números reales aleatorios de la misma forma que hicimos anteriormente.
matrix_4x5_one = np.random.rand(4, 5)
matrix_5x5_three = np.random.rand(5, 5)

# Mostramos por pantalla ambas matrices.
print(matrix_4x5_one)
print(matrix_5x5_three)

[[0.84043716 0.29292766 0.88813255 0.79421017 0.26858898]
 [0.25175584 0.16668672 0.37086229 0.64357812 0.62535539]
 [0.0141415  0.548484   0.01233987 0.33529341 0.48400515]
 [0.26971858 0.4275889  0.9319403  0.15737534 0.07214575]]
[[0.15186121 0.35388324 0.67797734 0.04393188 0.94239458]
 [0.96830619 0.30937832 0.55360295 0.54323867 0.0356159 ]
 [0.04818628 0.47868006 0.88079316 0.53529188 0.10976235]
 [0.2717013  0.93000114 0.62676266 0.77013896 0.5699359 ]
 [0.2704288  0.4233129  0.33455615 0.68846029 0.16570577]]


In [17]:
# La multiplicación entre ambas matrices es posible por el método dos, usando la función `dot`, ya que esta se puede realizar
# sobre matrices de distinto tamaño, el único requisito es que el número de columnas de la primera matriz sea igual al número
# de filas de la segunda matriz. Realizamos la multiplicación y mostramos el resultado para comprobarlo.
matrix_product_three_valid = matrix_4x5_one.dot(matrix_5x5_three)
print("El resultado de multiplicar estas dos matrices usando la función 'dot' es: \n" + str(matrix_product_three_valid))

El resultado de multiplicar estas dos matrices usando la función 'dot' es: 
[[0.7424914  1.66548698 2.10186341 1.4680268  1.39709545]
 [0.56148132 1.18143521 1.20220321 1.22630729 0.75432002]
 [0.7558312  0.69730923 0.69617515 0.89662526 0.30551427]
 [0.56217289 0.85073634 1.363198   0.91386252 0.47335107]]


In [18]:
# Sin embargo, si intentamos multiplicar ambas matrices por el método uno, es decir, usando el operador "*", nos dará error, ya
# que al ser dos matrices de distinto tamaño no puede ejecutar la multiplicación elemento a elemento porque habrá elementos que
# no se corresponden con ninguno. Podemos comprobarlo ejecutando el siguiente código:
matrix_product_four_no_valid = matrix_4x5_one * matrix_5x5_three

ValueError: operands could not be broadcast together with shapes (4,5) (5,5) 